"""Add externa_api_id to games table

Revision ID: d96dd0231705
Revises: 
Create Date: 2026-02-12 19:44:40.161815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd96dd0231705'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('external_api_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_games_external_api_id'), 'games', ['external_api_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_external_api_id'), table_name='games')
    op.drop_column('games', 'external_api_id')
    # ### end Alembic commands ###
