"""add deposits table

Revision ID: decaad4cd7f2
Revises: d96dd0231705
Create Date: 2026-06-02 18:44:51.339935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'decaad4cd7f2'
down_revision: Union[str, Sequence[str], None] = 'd96dd0231705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposits', sa.Column('stripe_payment_intent_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('deposits_stripe_payment_intend_id_key'), 'deposits', type_='unique')
    op.create_unique_constraint(None, 'deposits', ['stripe_payment_intent_id'])
    op.drop_column('deposits', 'stripe_payment_intend_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposits', sa.Column('stripe_payment_intend_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'deposits', type_='unique')
    op.create_unique_constraint(op.f('deposits_stripe_payment_intend_id_key'), 'deposits', ['stripe_payment_intend_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('deposits', 'stripe_payment_intent_id')
    # ### end Alembic commands ###
